name: NPM Build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install Dependencies
              run: npm install
            - name: Build Package
              run: npm run build
            - name: Run Linting
              run: npm run lint
